source=cursor.conf

exec-once=autoexec

blur=1
blur_layer=1
blur_optimized=1
shadows=1
layer_shadows=1
shadow_only_floating=0
border_radius=4
borderpx=2
no_radius_when_single=0
focused_opacity=0.9
unfocused_opacity=0.8
animations=1
layer_animations=1
enable_hotarea=1
hotarea_corner=0
numlockon=1
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
bind=SUPER,a,spawn,ai
bind=SUPER,b,spawn,browser
bind=SUPER,c,spawn,calculator
bind=SUPER,d,spawn,transmenu
bind=SUPER,e,spawn,editor
bind=SUPER,f,spawn,files
bind=SUPER,g,spawn,game
bind=SUPER,i,spawn,settings
bind=SUPER,l,spawn,powermenu
bind=SUPER,m,spawn,mail
bind=SUPER,n,spawn,news
bind=SUPER,o,toggleoverview
bind=SUPER,q,killclient
bind=SUPER,r,spawn,launcher
bind=SUPER,s,spawn,screenshot
bind=SUPER,t,spawn,topper
bind=SUPER,u,spawn,music
bind=SUPER,v,spawn,clipmenu
bind=SUPER,x,reload_config
bind=SUPER,z,spawn,terminal
