blur=1
blur_layer=1
blur_optimized=1
shadows=1
layer_shadows=1
shadow_only_floating=1
border_radius=4
no_radius_when_single=0
focused_opacity=0.9
unfocused_opacity=0.8
animations=1
layer_animations=1
enable_hotarea=1
hotarea_corner=0
numlockon=1
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
bind=SUPER,a,spawn,ai
bind=SUPER,b,spawn,browser
bind=SUPER,i,spawn,settings
bind=SUPER,q,killclient,
bind=SUPER,r,spawn,launcher
bind=SUPER,z,spawn,terminal
