source=./../../.cache/wal/colors-mango.conf
source=./cursor.conf

exec-once=autoexec

blur=1
blur_layer=1
shadows=1
layer_shadows=1
border_radius=4
borderpx=1
focused_opacity=0.9
unfocused_opacity=0.8
animations=1
layer_animations=1
animation_type_open=zoom
enable_hotarea=1
hotarea_corner=0
numlockon=1
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9
bind=SUPER,a,spawn,ai
bind=SUPER,b,spawn,browser
bind=SUPER,c,spawn,calculator
bind=SUPER,d,spawn,transmenu
bind=SUPER,e,spawn,editor
bind=SUPER,f,spawn,files
bind=SUPER,g,spawn,game
bind=SUPER,i,spawn,settings
bind=SUPER,l,spawn,powermenu
bind=SUPER,m,spawn,mail
bind=SUPER,n,spawn,news
bind=SUPER,o,toggleoverview
bind=SUPER,q,killclient
bind=SUPER,r,spawn,launcher
bind=SUPER,s,spawn,screenshot
bind=SUPER,t,spawn,topper
bind=SUPER,u,spawn,music
bind=SUPER,v,spawn,clipmenu
bind=SUPER,x,reload_config
bind=SUPER,z,spawn,terminal
bind=SUPER,Backspace,togglefloating
bind=SUPER,Return,togglefullscreen
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
windowrule=isfloating:1,isglobal:1,offsetx:100,offsety:100,width:0.3,height:0.5,appid:bottomright
windowrule=isfloating:1,isglobal:1,offsetx:100,offsety:100,width:0.3,height:0.5,title:^Picture.?in.?[Pp]icture$
windowrule=isfloating:1,appid:center
windowrule=isfloating:0,appid:libreoffice
windowrule=isfullscreen:1,appid:fullscreen
windowrule=isfullscreen:1,appid:screensaver
windowrule=isfullscreen:1,appid:steam_app
