swipe:
  3: 
    left: 
      command: 'xdo key_press -k 113; xdo key_press -k 100; sleep 0.2; xdo key_release -k 100; xdo key_release -k 113'
    right: 
      command: 'xdo key_press -k 113; xdo key_press -k 100; sleep 0.2; xdo key_release -k 100; xdo key_release -k 113'
    up: 
      command: 'xdotool key ctrl+shift+plus'
    down: 
      command: 'xdotool key ctrl+minus'
pinch:
  in:
    command: 'xdotool key ctrl+shift+plus'
  out:
    command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.5
  pinch: 0.2

interval:
  swipe: 0.2
  pinch: 0.2
