[[handlers]]
exec = "mpv %u"
terminal = true
regexes = ['(https://)?(www\.)?youtu(be\.com|\.be)/*.']

exec = "nsxiv-url %u"
terminal = true
regexes = ['/(https?:\/\/.*\.(?:png|jpg|jpeg|gif|png|svg))/i']
