autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
autocmd FocusGained,BufEnter * silent! checktime
autocmd VimLeave * mksession! $HOME/.config/vim/session.vim
colorscheme desert
filetype indent on
filetype plugin on
syntax on

let $LANG='en'
set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set clipboard=unnamed
set cmdheight=1
set complete+=kspell
set encoding=utf8
set expandtab
set ffs=unix,dos,mac
set foldcolumn=0
set hidden
set hlsearch
set history=500
set ignorecase
set incsearch
set langmenu=en
set laststatus=2
set lazyredraw
set linebreak
set listchars=space:·
set magic
set mat=2
set nobackup
set nocompatible
set noerrorbells
set noshowmode
set noswapfile
set nowritebackup
set number
set regexpengine=0
set ruler
set scrolloff=6
set shiftwidth=4
set showmatch
set showtabline=2
set smartcase
set smartindent
set smarttab
set statusline=
set statusline+=%#Visual#
set statusline+=\ %{mode()}\ 
set statusline+=%#Nontext#
set statusline+=\ %F%y%r%m\ 
set statusline+=%=
set statusline+=\ %{&fileencoding}\ 
set statusline+=%#Visual#
set statusline+=\ %p%%\ %l/%L,%c\ 
set t_Co=256
set t_vb=
set tabstop=4
set tm=500
set tw=500
set visualbell
set whichwrap+=<,>,[,]
set wildmenu
set wrap

highlight User1 guifg=#ffdad8  guibg=#880c0e
highlight User2 guifg=#000000  guibg=#f4905c
highlight User3 guifg=#292b00  guibg=#f4f597
highlight User4 guifg=#112605  guibg=#aefe7b
highlight User5 guifg=#051d00  guibg=#7dcc7d
highlight User6 guifg=#ffffff  guibg=#5b7fbb

map ; :
map <C-h> <C-W>h
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-l> <C-W>l
map <Space> <Leader>
nnoremap <F7> :setlocal spell!<CR>
nnoremap <F8> :set list!<CR>
nnoremap <F11> :source $HOME/.config/vim/session.vim<CR>
nnoremap <F12> :args $HOME/.config/vim/vimrc \| tab all<CR>
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>
nnoremap j gj
nnoremap k gk
