let $LANG='en'
set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set clipboard=unnamedplus
set cmdheight=1
set complete+=kspell
set encoding=utf8
set ffs=unix,dos,mac
set foldcolumn=0
set hidden
set hlsearch
set history=500
set ignorecase
set incsearch
set langmenu=en
set laststatus=2
set lazyredraw
set linebreak
set listchars=space:·,tab:>·
set magic
set mat=2
set mouse=a
set nobackup
set nocompatible
set noemoji
set noerrorbells
set noshowmode
set noswapfile
set nowritebackup
set number
set omnifunc=syntaxcomplete#Complete
set regexpengine=0
set relativenumber
set ruler
set runtimepath^=~/.local/share/vim
set scrolloff=0
set shiftwidth=8
set showmatch
set smartcase
set smartindent
set smarttab
set statusline=
set statusline+=%#Visual#
set statusline+=\ %{mode()}\ 
set statusline+=%#Nontext#
set statusline+=\ %F%y%r%m\ 
set statusline+=%=
set statusline+=\ %{&fileencoding}\ 
set statusline+=%#Visual#
set statusline+=\ %p%%\ %l/%L,%c\ 
set t_Co=256
set t_vb=
set tabstop=8
set tm=500
set tw=500
set viminfo='10,<100,:100,%,n~/.local/state/vim/viminfo
set visualbell
set whichwrap+=<,>,[,]
set wildignore=*.docx,*.gif,*.img,*.jpg,*.png,*.pdf,*.pyc,*.o,*.xlsx
set wildmenu
set wrap

map <Space> <Leader>
map <Leader>. :set list!<CR>
map <Leader><Esc> :nohlsearch<CR>
map <Leader>a ggVG
map <Leader>o :Files<CR>
map <Leader>p :NERDTreeToggle<CR>
map <Leader>q :q!<CR>
map <Leader>w :w!<CR>
imap <C-v> <C-r>+
imap <C-z> <C-o>u

filetype indent on
filetype plugin on
syntax on

autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
autocmd FocusGained,BufEnter * silent! checktime
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif
autocmd VimLeave * mksession! ~/.local/state/vim/vimsession

if empty(glob('~/.local/state/vim'))
	silent !mkdir -p ~/.local/state/vim
endif

if empty(glob('~/.local/share/vim/autoload/plug.vim'))
	silent !curl -fLo ~/.local/share/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin()
Plug 'ap/vim-css-color'
Plug 'jasonccox/vim-wayland-clipboard'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'mg979/vim-visual-multi'
Plug 'mhinz/vim-startify'
Plug 'preservim/nerdtree'
Plug 'tpope/vim-surround'
call plug#end()
