[config]

[templates.dmenu]
input_path = '~/.config/matugen/dmenu.sh'
output_path = '~/.cache/wal/colors.sh'

[templates.dunst]
input_path = '~/.config/matugen/dunst'
output_path = '~/.config/dunst/dunstrc.d/colors'
post_hook = 'dunstctl reload'
 
[templates.foot]
input_path = '~/.config/matugen/foot.ini'
output_path = '~/.config/foot/colors.ini'

[templates.fuzzel]
input_path = '~/.config/matugen/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.hyprland]
input_path = '~/.config/matugen/hyprland.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/hyprlock.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/mako'
output_path = '~/.config/mako/colors'
post_hook = 'makoctl reload'

[templates.mango]
input_path = '~/.config/matugen/mango.conf'
output_path = '~/.config/mango/colors.conf'
post_hook = 'mmsg -d reload_config'

[templates.niri]
input_path = '~/.config/matugen/niri.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.pywalfox]
input_path = '~/.config/matugen/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.waybar]
input_path = '~/.config/matugen/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.xresources]
input_path = '~/.config/matugen/xorg'
output_path = '~/.config/xorg/colors'
post_hook = 'xrdb -merge ~/.config/xorg/colors'
