[config]

[templates.dunst]
input_path = '~/.config/matugen/dunst'
output_path = '~/.config/dunst/dunstrc.d/colors'
post_hook = 'dunstctl reload'

[templates.fuzzel]
input_path = '~/.config/matugen/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.hypr]
input_path = '~/.config/matugen/hypr.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/mako'
output_path = '~/.config/mako/colors'
post_hook = 'makoctl reload'

[templates.mango]
input_path = '~/.config/matugen/mango.conf'
output_path = '~/.config/mango/colors.conf'
post_hook = 'mmsg -d reload_config'

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'
