[config]

[templates.dunst]
input_path = '~/.config/matugen/dunst'
output_path = '~/.config/dunst/dunstrc.d/colors'
post_hook = 'dunstctl reload'

[templates.mako]
input_path = '~/.config/matugen/mako'
output_path = '~/.config/mako/colors'
post_hook = 'makoctl reload'

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'
