services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    network_mode: host
    environment:
      OLLAMA_BASE_URL: http://127.0.0.1:11434
      WEBUI_AUTH : False
    ports:
      - 3000:8080
    volumes:
      - /etc/open-webui:/app/backend/data
