services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main-slim
    restart: unless-stopped
    environment:
      WEBUI_AUTH: False
    ports:
      - 3000:8080
    volumes:
      - /etc/open-webui:/app/backend/data
