services:
  sub-store:
    container_name: sub-store
    image: xream/sub-store:http-meta
    restart: unless-stopped
    network_mode: host
    environment:
      HOST: 127.0.0.1
      PORT: 9876
      SUB_STORE_BACKEND_API_HOST: 127.0.0.1
      SUB_STORE_BACKEND_API_PORT: 3000
      SUB_STORE_BACKEND_MERGE: true
      SUB_STORE_CORS_ALLOWED_ORIGINS: http://127.0.0.1:3000
      SUB_STORE_FRONTEND_BACKEND_PATH: /12345678910987654321
    volumes:
      - /etc/sub-store:/opt/app/data
