source = colors.conf

general {
	hide_cursor = true
	ignore_empty_input = true
}

auth {
	fingerprint {
		enabled = true
	}
}

animations {
	bezier = linear, 1, 1, 0, 0
	animation = fadeIn, 1, 3, linear
	animation = fadeOut, 1, 3, linear
	animation = inputFieldDots, 1, 2, linear
}

background {
	path = screenshot
	blur_passes = 2
}

image {
	path = ~/Pictures/wallpapers/wallpaper
	size = 150
	rounding = -1
	border_size = 10
	border_color = $primary
	position = 0, 10%
	halign = center
	valign = center
	shadow_passes = 5
}

input-field {
	size = 15%, 5%
	outline_thickness = 3
	outer_color = $outline
	inner_color = $surface
	font_color = $on_surface
	font_family = terminal
	fade_on_empty = false
	placeholder_text = <i>󱅞 Log in as <b>$USER</b></i>
	rounding = 15
	check_color = $on_primary
	fail_color = $error
	fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
	capslock_color = $error
	position = 0, -10%
	halign = center
	valign = center
}

label {
	text = cmd[update:10000] fortune -as
	color = $tertiary
	font_size = 16
	font_family = terminal
	position = 0, 4%
	halign = center
	valign = bottom
}
