#!/bin/sh

s=" | " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
mimetype=$(file -b --mime-type -- "$1")
geometry="${2}x${3}"
tags=$(identify -format '%[IPTC:2:25]' ":$1" | tr ';' ',')

echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${mimetype}${s}${filename}"

if [ -n "$id" ]; then
	lf -remote "send $id select  \"$filename\"  "
fi
