#!/bin/sh

s=" | " # field separator

exec 2>/dev/null

filename=$(basename -- "$4")
filesize=$(du -Hh -- "$4" | cut -f 1)
geometry=$(identify -format "%wx%h" "$4")

echo "${filesize}${s}${geometry}${s}${filename}"

if [ -n "$id" ]; then
	lf -remote "send $id select  \"$filename\"  "
fi
