[[ $- != *i* ]] && return

PS1='\[$(tput sc; tput setaf 3; printf "%*s" $COLUMNS $(__git_ps1); tput rc)\]\[$(tput setaf 2)\]\u@\h:\[$(tput setaf 1)\]\w>\[$(tput sgr0)\] '

alias ,,='cd -'
alias ..='cd ..'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip --color=auto'
alias ll='ls -lahF --group-directories-first'
alias ls='ls --color=auto'

eval "$(zoxide init bash)"

if [ -f ~/.cache/wal/sequences ]; then
	(cat ~/.cache/wal/sequences &)
fi
