[manager]

prepend_keymap = [
	{ on = [ "g", "m" ],        run = "cd $XDG_RUNTIME_DIR/gvfs",           desc = "Open SMB mount" },
	{ on = [ "g", "t" ],        run = "cd $HOME/.local/share/Trash",        desc = "Open trash bin" },
	{ on = [ "g", "u" ],        run = "cd /run/media/$USER",                desc = "Open USB mount" },
]
