[manager]

prepend_keymap = [
	{ on = [ "g", "m" ],       run = "cd /run/media/$USER",     desc = "Goto /run/media/$USER" },
	{ on = [ "g", "t" ],       run = "cd ~/.local/share/Trash",     desc = "Goto ~/.local/share/Trash" },
]
