xrandr --output Virtual1 --mode 1920x1080 --rate 100
clash &
fcitx5 &
keyboard &
statusbar &
wallpaper &
xcompmgr &
xrdb -merge ~/.config/xorg/xresources &
xset s 600 &
xsidle slock &
session=${1:-dwm}
case $session in
	dwm   ) exec dwm ;;
	gnome ) exec gnome-session ;;
	kde   ) exec startplasma-x11 ;;
	xfce  ) exec startxfce4 ;;
	*     ) exec $1 ;;
esac
