clash &
keymap &
setleds -D +num &
unclutter &
xinput set-prop 16 319 1 &
xinput set-prop 16 348 1 &
xset r rate 300 30 s 600 &

case $1 in
	dwm)
		dunst &
		fcitx5 &
		statusbar &
		udiskie &
		wallpaper &
		xautolock -time 5 -locker locker &
		xcompmgr &
		exec dwm
		;;
	gnome)
		exec gnome-session
		;;
	kde)
		exec startplasma-x11
		;;
	xfce)
		gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
		gsettings set org.gnome.desktop.interface gtk-theme 'Chicago95'
		gsettings set org.gnome.desktop.interface icon-theme 'Chicago95'
		exec startxfce4
		;;
esac
